name: Build minieap-sysu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc-multilib

    - name: Set up OpenWRT SDK for aarch64
      run: |
        wget https://downloads.openwrt.org/releases/22.03.5/targets/rockchip/armv8/openwrt-sdk-22.03.5-rockchip-armv8_gcc-11.2.0_musl.Linux-x86_64.tar.xz
        tar xf openwrt-sdk-22.03.5-rockchip-armv8_gcc-11.2.0_musl.Linux-x86_64.tar.xz
        mv openwrt-sdk-22.03.5-rockchip-armv8_gcc-11.2.0_musl.Linux-x86_64 openwrt-sdk
        echo "PATH=$PATH:$PWD/openwrt-sdk/staging_dir/toolchain-aarch64_generic_gcc-11.2.0_musl/bin" >> $GITHUB_ENV

    - name: Build project
      run: |
        export CROSS_COMPILE=aarch64-openwrt-linux-
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: minieap
        path: minieap
