name: Build minieap-sysu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc-multilib

    - name: Set up OpenWRT SDK for aarch64
      run: |
        wget https://downloads.openwrt.org/releases/23.05.2/targets/rockchip/armv8/openwrt-sdk-23.05.2-rockchip-armv8_gcc-12.3.0_musl.Linux-x86_64.tar.xz
        tar xf openwrt-sdk-23.05.2-rockchip-armv8_gcc-12.3.0_musl.Linux-x86_64.tar.xz
        mv openwrt-sdk-23.05.2-rockchip-armv8_gcc-12.3.0_musl.Linux-x86_64 openwrt-sdk
        echo "$PWD/openwrt-sdk/staging_dir/toolchain-aarch64_generic_gcc-12.3.0_musl/bin" >> $GITHUB_PATH

    - name: Build project
      run: |
        export STAGING_DIR=$PWD/openwrt-sdk/staging_dir
        export PATH=$STAGING_DIR/toolchain-aarch64_generic_gcc-12.3.0_musl/bin:$PATH
        export CROSS_COMPILE=aarch64-openwrt-linux-musl-
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: minieap
        path: minieap
